golf-db:
  outputs:
    prod:
      dataset: staging
      fixed_retries: 1
      location: asia-northeast1
      method: oauth
      priority: interactive
      project: golf-db-361606
      threads: 3
      type: bigquery

    dev:
      dataset: staging
      fixed_retries: 1
      location: asia-northeast1
      method: oauth
      priority: interactive
      project: golf-db-361606
      threads: 3
      type: bigquery

  target: dev


elementary:
  outputs:
    default:
      type: "bigquery"
      project: "golf-db-361606"
      dataset: "elementary"
      method: "oauth"  # Configure your auth method and add the required fields according to https://docs.getdbt.com/reference/warehouse-setups/bigquery-setup#authentication-methods
      threads: 3