name: 'dbt_jobs'

config-version: 2
version: '0.1'
require-dbt-version: [">=1.5.0", "<2.0.0"]

profile: 'golf-db'

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  dbt_jobs:
      staging:
        +materialized: view
        +schema: "staging"
      marts:
        +materialized: table
        +schema: "datamart"
